CONTRIBUTING.md

Cria CONTRIBUTING.md - Fix #104

---

javascripts/events.js

Adicionado o local principal do evento e foram corrigido os dias do evento.

Correção dos dias e local da Python NE 2015

---

index.html
javascripts/events.js
javascripts/main.js

Resolves #113

---

javascripts/events.js

Acrescenta o workshop Análise de Vulnerabilidade em Ambientes Wireless, a ser realizado
na faculdade Bandtec em 16-06-2015.
Signed-off-by: Kleber Hamada Sato <kleberhs007@yahoo.com>

Acrescenta workshop da Bandtec de 16-06-2015

---

javascripts/events.js

Acrescenta workshops da faculdade Bandtec dos dias 17/06 e 18/06/2015.
Signed-off-by: Kleber Hamada Sato <kleberhs007@yahoo.com>

Acrescenta workshops da Bandtec

---

README.md
javascripts/events.js

Corrige link_embeds habilitando navegação dos mapas e insere instrução no Readme

Corrige link_embeds e insere instrução em Readme

---

javascripts/events.js

Fix pr 129

---

javascripts/events.js

Add Caipira Ágil.

---

javascripts/events.js

:ballot_box_with_check: Remove PHPESTE

Remove old event (PHPESTE)

---

javascripts/events.js

Add new event:
Hackday Hobbit Apprentice at Raul Hacker Club.

Add new event - Hackday Hobbit Apprentice

---

javascripts/events.js

Add new event:
PhpConference Brasil 2015

Add PhpConference Brasil 2015

---

javascripts/events.js

17/10 Front in Manaus
24/10 DevFest Sudeste 2015 em BH
24/10 PHPRio Talks
31/10 WordCamp Porto Alegre 2015

Add out 15

---

javascripts/events.js

removed event "Hackday Hobbit Apprentice"

removed event

---

javascripts/events.js

Adicionando API Experience

---

javascripts/events.js

Remove eventos anteriores à 18/10

Removendo eventos antigos

---

.travis.yml
README.md

https://github.com/svenkreiss/html5validator

Travis-CI para validar os Pull Requests

---

javascripts/main.js

Resolve erro: Uncaught TypeError: Events.getByTitulo is not a function

Volta a aparecer mapa dinâmico ao clicar no mapa estático

---

javascripts/data/events.json

[14-11-15] Insere PHParty 7 - RJ

Insere PHParty 7 - RJ

---

javascripts/data/events.json

[07-11] Hackaflag Sao Paulo
[07-11] 1º Meetup Devparaná
[11-11] API Experience

Remove eventos já realizados

---

javascripts/events.js

Exibir somente eventos futuros, comparando "dataFim" com a data atual do computador.
Organizando os eventos por "dataInicio" em ordem crescente.

Filtrar e organizar eventos por data

---

javascripts/events.js

Reverts saiadecasa/saiadecasa.github.io#201

Revert "Filtrar e organizar eventos por data"

---

javascripts/data/events.json

Adds new event > RuPy Campinas

---

index.html
javascripts/events.js
javascripts/main.js
stylesheets/custom_styles.css

Adicionada funcionalidade de trajetos/distância via Google Maps. Essa funcionalidade foi iniciada na PR #210 por @LeoPersan, boa parte do código peguei dele -- com algumas modificações comentadas na própria PR.
As rotas e distância são carregados assim que o usuário autoriza a geolocalização. Enquanto ele não autoriza (ou se ele bloquear), os eventos são listados normalmente.
- Melhorado template de eventos;
- Adicionado filtro de eventos;
- Adicionada propriedade 'distancia' nos eventos;
- Usando event delegation para ouvir o clique das imagens.
(Se eu fiz algo errado nessa PR, é só avisar que arrumo :smile:)

Trajeto de carro Google Maps e cálculo da distância. v2

---

javascripts/data/events.json

* Added 
- BrazilJS Conf 2016 - Edição Olimpíadas

Adds new event

---

javascripts/data/events.json

Removendo o evento Meetup Cianorte que ja foi reliazado.

removendo evento que ja ocorreu

---

javascripts/data/events.json

Evento "Temporada-Agile" removido pois ele já foi realizado.

removendo temporada-agile

---

javascripts/data/events.json

Removi a Roadsec Brasilia do Calendário :)

Removi Roadsec Brasilia

---

javascripts/data/events.json

Adicionei o encontro de março do GruPy-SP :)

Adicionei encontro do GruPy-SP

---

javascripts/data/events.json

Adicionei o Meetup Google Cloud + Big Data do Tech Trends :)

Adicionei o Google Cloud + Big Data

---

javascripts/data/events.json

Adicionado o evento: RoadSec Manaus.

adicionando roadsec em manuas

---

javascripts/data/events.json

Adds event

---

javascripts/data/events.json

Removendo todos os eventos que já foram realizados :smile:

removendo eventos ja realizados

---

javascripts/data/events.json

Removendo evento que já ocorreu.

removendo evento

---

javascripts/data/events.json

Adicionando novo evento: roadsec fortaleza

add roadsec fortaleza

---

javascripts/data/events.json

* Removes 
- Roadsec Teresina 
- FLISOL Maringá
- FrontInCuiabá

Removes old events

---

javascripts/data/events.json

Removido o evento 6º Campinas Front-End Meetup

Removendo evento já ocorrido

---

javascripts/data/events.json

Removendo o evento PHPSP que já foi realizado.

removendo evento que ja ocorreu PHPSP

---

javascripts/data/events.json

Removido evento vencido

---

javascripts/data/events.json

Add BeerJS - Sao Jose dos Campos

---

javascripts/data/events.json

* 6º Encontro Regional de Computação - Compweek
* Roadsec Natal

Removendo eventos já ocorridos

---

javascripts/data/events.json

Remove Roadsec Recife e BeerJS

---

javascripts/data/events.json

Não sei se coordenadas estão corretas, olhei bastante aqui e não tenho certeza se inseri corretamente.
Nos últimos PRs não sei porque mas não estou conseguindo pegar as coordenadas certas.

Insere SampaJS

---

javascripts/data/events.json

remove Google Cloud

---

javascripts/data/events.json

Removendo eventos já realizados:
1. BrazilJS 
2 RoadSec BH

Removendo eventos já realizados

---

javascripts/data/events.json

Removes event

---

javascripts/data/events.json

No ultimo pull request eu removi um evento que ainda não tinha acontecido, que no caso é a MiniConf Elixir,
e deixei um evento que já tinha ocorrido.

arrumando ultimo pull request

---

.travis.yml
package.json

- Changed node version to last one (6)
- Updated htmlhint to last version
Issue #298

Fixing Travis CI build

---

index.html
javascripts/events.js
javascripts/main.js
stylesheets/custom_styles.css

Tomei a liberdade de implementar a ordenação por distância sugerida na issue #249.
Não sei se o visual do menu ficou legal, e se poderia ter algum tipo de animação ao mudar a ordenação...

Implementado menu de ordenação de eventos. Fix #249

---

javascripts/data/events.json

Same address, but the event will be in another room.

Change Meetup Share location.

---

javascripts/data/events.json

* Old events
- Campinas Front-End Meetup
- Meetup Share

Removes events

---

javascripts/data/events.json

Remoção do evento já ocorrido no arquivo events.json

Remoção de evento realizado

---

javascripts/data/events.json

Reverts saiadecasa/saiadecasa.github.io#375

Revert "Adicionando 2° Hackathon Campinas"

---

javascripts/data/events.json

Não vamos deixar o projeto morrer galera!

Adicionando QCon e removendo eventos realizados

---

javascripts/data/events.json

Adicionado novo evento que vai ocorrer em Porto Alegre

Adicionado novo evento DevDay RS - Communities

---

javascripts/data/events.json

05 & 06 DE OUTUBRO, HOTEL UNIQUE - SÃO PAULO
A MAIOR CONFERÊNCIA DEV DA AMÉRICA LATINA

Inserindo InterCon 2018

---

javascripts/data/events.json

Adicionado o evento WordCamp São Paulo
Closes #481

Wordcamp São Paulo 2018 adicionado

---

javascripts/data/events.json

Solicitado em #478 
Deixo uma sugestoes ao projeto, adicionar por exemplo [editorconfig](https://editorconfig.org/) ou [prettier](https://prettier.io/) ou similares, somente para padronizar os arquivos (principalmente o `events.json`)
Abraços

Adicionado GDG Campinas AndroidFest 2018

---

javascripts/data/events.json

Adiciona evento BrasilJS Belo Horizonte

---

javascripts/data/events.json

Evento PHP Conference Brasil 2018 adicionado.

Adicionando PHP Conference Brasil 2018

---

package.json

Algumas versoes dos pacotes do npm estavam com grande risco de
vulnerabilidade. Esta atualizacao melhora o nivel de seguranca do
projeto.

Atualizando versoes dos pacotes do npm

---

javascripts/data/events.json

Added React Conf Brasil 2018

---

javascripts/data/events.json

Adicionei o evento UX Team Summit

Hacktoberfest: UX Team Summit #501

---

javascripts/data/events.json

Adiciona o evento RD Summit 2018

 Hacktoberfest: RD Summit #496

---

javascripts/data/events.json

Adiciona DevFest BH
Closes #497

Hacktoberfet: Devfest BH #497

---

javascripts/data/events.json

- Pequenas correções na identação;

Adicionando GDG DevFest Parana 2018

---

javascripts/data/events.json

removendo APICON

---

javascripts/data/events.json

Hacktoberfet: Latinoware #495

---

javascripts/data/events.json

Removendo dois eventos antigos:
- Latinoware 2018
- IT Expo 2018

remove old events - (Latinoware and IT Expo 2018)

---

javascripts/data/events.json

Hacktoberfest: UX Conf BR #499

---

index.html

Fix #529: inclui API KEY para staticmap Google

---

javascripts/data/events.json

JS Day Brazil 2018 - Chapter Recife

---

javascripts/data/events.json

Eventos removidos:
- BrazilJS on the road Belo Horizonte
- Women Dev Summit 2018
- UX Team Summit 2018

Remove eventos passados

---

javascripts/data/events.json

Remoção de eventos antigos:
- GDG DevFest Paraná 2018
-Americana Tech Conf
-DevOpsDay Belém 2018
-Boteco PHP RJ

Remoção de eventos antigos

---

.travis.yml
javascripts/data/events.json
package-lock.json
package.json

Adiciona JSON Code Style

---

CONTRIBUTING.md
package-lock.json
package.json

This version we'll be able to fix json files.

Update JSONCS to version 0.1.1

---

javascripts/data/events.json

Removing past event
